import {
  DAI_E_DepositAddress,
  WAVAXDepositAddress,
  BUSDAddress,
  WBNB_Address,
  DAIFallsTrancheMasterAddress2,
  DAIFallsMasterWTFAddress2,
  DAIBenqiStrategyAddress2,
  DAITraderJoeStrategyAddress2,
  WAVAXFallsTrancheMasterAddress2,
  WAVAXFallsMasterWTFAddress2,
  WAVAXBenqiStrategyAddress2,
  WAVAXTraderJoeStrategyAddress2,
  BUSDTripleStratTrancheMasterAddress,
  BUSDTripleStratMasterWTFAddress,
  BUSDTriple_AlpacaStrategyAddress,
  BUSDTriple_VenusStrategyAddress,
  BUSDTriple_StargateStrategyAddress,
  BNB_Only_Falls_TrancheMasterAddress,
  BNB_Only_Falls_MasterWTFAddress,
  BNB_Only_Falls_AlpacaStrategyAddress,
  BNB_Only_Falls_VenusStrategyAddress,
  USDC_Address_AVAX,
  Polygon_Uncollateralized_TrancheMasterAddress,
  Polygon_Uncollateralized_MasterWTFAddress,
  USDC_Address_Matic,
  Polygon_Uncollateralized_ClearpoolFolkvangStrat,
  Polygon_Uncollateralized_ClearpoolAmberStrat,
  Polygon_Uncollateralized_ClearpoolAurosStrat,
  Polygon_Uncollateralized_ClearpoolBastionStrat,
  Polygon_Uncollateralized_ClearpoolParallelStrat,
  AVAX_USDC_TrancheMasterAddress,
  AVAX_USDC_MasterWTFAddress,
  AVAX_USDC_StargateStrategyAddress,
  AVAX_USDC_BenqiStrategyAddress,
  AVAX_USDC_TraderJoeStrategyAddress,
} from "./address";
// import Tranches from "./abis/TrancheMaster.json";
// import MC_Tranches from "./abis/MC_TrancheMaster.json";
import AR_Tranches from "./abis/AR_TrancheMaster.json";
import MasterChef from "./abis/MasterChef.json";
import WTF from "./abis/WTF.json";
import AVAXTrancheMasterAutorollABI from "./abis/AVAXTrancheMasterAutoroll.json";
import { Market, NETWORKS } from "../types";

type NETWORKS_TYPE = typeof NETWORKS[keyof typeof NETWORKS];
const NETWORK = "MAINNET" as NETWORKS_TYPE; //exposing network switch here, since this is the main control config,
//but since product is live, this should never change

export const MarketList: Market[] = [
  {
    portfolio: "Polygon Falls",
    network: 137,
    wrap: false,
    autorollImplemented: true,
    isMulticurrency: false,
    assets: ["USDC"],
    tokens: [],
    listingDate: "2022/11/9",
    tranches: [],
    trancheCount: 3,
    tvl: "",
    totalTranchesTarget: "",
    status: "",
    nextTime: "",
    address: Polygon_Uncollateralized_TrancheMasterAddress[NETWORK],
    abi: AVAXTrancheMasterAutorollABI,
    masterChefAbi: MasterChef.abi,
    masterChefAddress: Polygon_Uncollateralized_MasterWTFAddress[NETWORK],
    pools: [],
    depositAssetAddress: USDC_Address_Matic[NETWORK],
    depositAssetAddresses: [],
    depositAssetAbi: WTF.abi,
    strategyFarms: [
      {
        farmName: "Clearpool Folkvang",
        shares: 0.2,
        sAddress: Polygon_Uncollateralized_ClearpoolFolkvangStrat[NETWORK],
        apiKey: "cpool_folkvang_usdc",
      },
      {
        farmName: "Clearpool Amber",
        shares: 0.2,
        sAddress: Polygon_Uncollateralized_ClearpoolAmberStrat[NETWORK],
        apiKey: "cpool_amber_usdc",
      },
      {
        farmName: "Clearpool Auros",
        shares: 0.2,
        sAddress: Polygon_Uncollateralized_ClearpoolAurosStrat[NETWORK],
        apiKey: "cpool_auros_usdc",
      },
      {
        farmName: "Clearpool Bastion",
        shares: 0.2,
        sAddress: Polygon_Uncollateralized_ClearpoolBastionStrat[NETWORK],
        apiKey: "cpool_bastion_usdc",
      },
      {
        farmName: "Clearpool Parallel",
        shares: 0.2,
        sAddress: Polygon_Uncollateralized_ClearpoolParallelStrat[NETWORK],
        apiKey: "cpool_parallel_usdc",
      },
    ],
    strategyBlurbs: [
      "Clearpool provides institutional borrowers with fast, flexible and efficient access to unsecured liquidity from a diversified and decentralized network of global lenders. (https://clearpool.finance)",
    ],
    subgraphURL: "https://apipolygon.waterfalldefi.org/subgraphs/name/waterfall/maticUsdcClearpool",
    isRetired: false,
  },
  {
    portfolio: "BNB Falls",
    network: 56,
    wrap: true,
    autorollImplemented: true,
    isMulticurrency: false,
    assets: ["WBNB"], //changed to array for multicurrency
    tokens: [],
    listingDate: "2022/07/21",
    tranches: [],
    trancheCount: 3,
    tvl: "",
    totalTranchesTarget: "",
    status: "",
    nextTime: "",
    address: BNB_Only_Falls_TrancheMasterAddress[NETWORK],
    abi: AR_Tranches.abi, //tranches has autoPrincipal even though autoroll not enabled, so must use autoroll ABI
    masterChefAbi: MasterChef.abi,
    masterChefAddress: BNB_Only_Falls_MasterWTFAddress[NETWORK],
    pools: [],
    depositAssetAddress: WBNB_Address[NETWORK],
    depositAssetAddresses: [],
    depositAssetAbi: WTF.abi,
    // strategyAddress: StrategyAddress[NETWORK],
    // strategyAbi: StrategyAbi,
    strategyFarms: [
      {
        farmName: "Alpaca BNB",
        shares: 0.7,
        sAddress: BNB_Only_Falls_AlpacaStrategyAddress[NETWORK],
        apiKey: "alpaca_bnb",
      },
      {
        farmName: "Venus BNB",
        shares: 0.3,
        sAddress: BNB_Only_Falls_VenusStrategyAddress[NETWORK],
        apiKey: "venus_bnb",
      },
    ],
    strategyBlurbs: [
      "Alpaca Finance is the largest lending protocol allowing leveraged yield farming on BNB Chain and Fantom. (https://www.alpacafinance.org)",
      "Venus enables users to utilize their cryptocurrencies by supplying collateral to the network that may be borrowed by pledging over-collateralized cryptocurrencies. (https://venus.io)",
    ],
    subgraphURL: "https://api2.waterfalldefi.org/subgraphs/name/waterfall/bsc-bnb",
  },
  {
    portfolio: "DAI Falls",
    network: 43114,
    wrap: false,
    autorollImplemented: true,
    isMulticurrency: false,
    assets: ["DAI.e"],
    tokens: [],
    listingDate: "2022/2/28",
    tranches: [],
    trancheCount: 3,
    tvl: "",
    totalTranchesTarget: "",
    status: "",
    nextTime: "",
    address: DAIFallsTrancheMasterAddress2[NETWORK],
    abi: AVAXTrancheMasterAutorollABI,
    masterChefAbi: MasterChef.abi,
    masterChefAddress: DAIFallsMasterWTFAddress2[NETWORK],
    pools: [],
    depositAssetAddress: DAI_E_DepositAddress[NETWORK],
    depositAssetAddresses: [],
    depositAssetAbi: WTF.abi,
    strategyFarms: [
      {
        farmName: "Benqi DAI.e",
        shares: 0.91,
        sAddress: DAIBenqiStrategyAddress2[NETWORK],
        apiKey: "qi_dai",
      },
      {
        farmName: "Trader Joe DAI.e",
        shares: 0.09,
        sAddress: DAITraderJoeStrategyAddress2[NETWORK],
        apiKey: "joe_dai_e",
      },
    ],
    strategyBlurbs: [
      "The BENQI Liquidity Market (BLM) protocol enables users to effortlessly lend, borrow, and earn interest with their digital assets. (https://benqi.fi)",
      "Trader Joe provides users with a true one-stop-shop DeFi experience on Avalanche. (https://traderjoexyz.com)",
    ],
    subgraphURL: "https://api3.waterfalldefi.org/subgraphs/name/waterfall/qiJoe_dai",
    isRetired: false,
  },
  {
    portfolio: "AVAX Falls",
    network: 43114,
    wrap: true,
    autorollImplemented: true,
    isMulticurrency: false,
    assets: ["WAVAX"],
    tokens: [],
    listingDate: "2022/2/28",
    tranches: [],
    trancheCount: 3,
    tvl: "",
    totalTranchesTarget: "",
    status: "",
    nextTime: "",
    address: WAVAXFallsTrancheMasterAddress2[NETWORK],
    abi: AVAXTrancheMasterAutorollABI,
    masterChefAbi: MasterChef.abi,
    masterChefAddress: WAVAXFallsMasterWTFAddress2[NETWORK],
    pools: [],
    depositAssetAddress: WAVAXDepositAddress[NETWORK],
    depositAssetAddresses: [],
    depositAssetAbi: WTF.abi,
    strategyFarms: [
      {
        farmName: "Benqi AVAX",
        shares: 0.7,
        sAddress: WAVAXBenqiStrategyAddress2[NETWORK],
        apiKey: "qi_avax",
      },
      {
        farmName: "Trader Joe AVAX",
        shares: 0.3,
        sAddress: WAVAXTraderJoeStrategyAddress2[NETWORK],
        apiKey: "joe_avax",
      },
    ],
    strategyBlurbs: [
      "The BENQI Liquidity Market (BLM) protocol enables users to effortlessly lend, borrow, and earn interest with their digital assets. (https://benqi.fi)",
      "Trader Joe provides users with a true one-stop-shop DeFi experience on Avalanche. (https://traderjoexyz.com)",
    ],
    subgraphURL: "https://api3.waterfalldefi.org/subgraphs/name/waterfall/qiJoe_avax",
    isRetired: false,
  },
  {
    portfolio: "BUSD Falls",
    network: 56,
    wrap: false,
    autorollImplemented: true,
    isMulticurrency: false,
    assets: ["BUSD"],
    tokens: [],
    listingDate: "2022/4/25",
    tranches: [],
    trancheCount: 3,
    tvl: "",
    totalTranchesTarget: "",
    status: "",
    nextTime: "",
    address: BUSDTripleStratTrancheMasterAddress[NETWORK],
    abi: AR_Tranches.abi,
    masterChefAbi: MasterChef.abi,
    masterChefAddress: BUSDTripleStratMasterWTFAddress[NETWORK],
    pools: [],
    depositAssetAddress: BUSDAddress[NETWORK],
    depositAssetAddresses: [],
    depositAssetAbi: WTF.abi,
    strategyFarms: [
      {
        farmName: "Alpaca BUSD",
        shares: 0.35,
        sAddress: BUSDTriple_AlpacaStrategyAddress[NETWORK],
        apiKey: "alpaca",
      },
      {
        farmName: "Venus BUSD",
        shares: 0.15,
        sAddress: BUSDTriple_VenusStrategyAddress[NETWORK],
        apiKey: "venus",
      },
      {
        farmName: "Stargate BUSD",
        shares: 0.5,
        sAddress: BUSDTriple_StargateStrategyAddress[NETWORK],
        apiKey: "stargate_bnb_busd",
      },
    ],
    strategyBlurbs: [
      "Alpaca Finance is the largest lending protocol allowing leveraged yield farming on BNB Chain and Fantom. (https://www.alpacafinance.org)",
      "Venus enables users to utilize their cryptocurrencies by supplying collateral to the network that may be borrowed by pledging over-collateralized cryptocurrencies. (https://venus.io)",
      "Stargate is a fully composable liquidity transport protocol that lives at the heart of Omnichain DeFi (https://stargate.finance)",
    ],
    subgraphURL: "https://api2.waterfalldefi.org/subgraphs/name/waterfall/bsc-busd",
    isRetired: false,
  },
  {
    portfolio: "USDC Falls",
    network: 43114,
    wrap: false,
    autorollImplemented: true,
    isMulticurrency: false,
    assets: ["USDC"],
    tokens: [],
    listingDate: "2022/5/20",
    tranches: [],
    trancheCount: 3,
    tvl: "",
    totalTranchesTarget: "",
    status: "",
    nextTime: "",
    address: AVAX_USDC_TrancheMasterAddress[NETWORK],
    abi: AVAXTrancheMasterAutorollABI,
    masterChefAbi: MasterChef.abi,
    masterChefAddress: AVAX_USDC_MasterWTFAddress[NETWORK],
    pools: [],
    depositAssetAddress: USDC_Address_AVAX[NETWORK],
    depositAssetAddresses: [],
    depositAssetAbi: WTF.abi,
    strategyFarms: [
      {
        farmName: "Stargate USDC",
        shares: 0.34,
        sAddress: AVAX_USDC_StargateStrategyAddress[NETWORK],
        apiKey: "stargate_avax_usdc",
      },
      {
        farmName: "Benqi USDC",
        shares: 0.33,
        sAddress: AVAX_USDC_BenqiStrategyAddress[NETWORK],
        apiKey: "qi_usdc",
      },
      {
        farmName: "Trader Joe USDC",
        shares: 0.33,
        sAddress: AVAX_USDC_TraderJoeStrategyAddress[NETWORK],
        apiKey: "joe_usdc",
      },
    ],
    strategyBlurbs: [
      "The BENQI Liquidity Market (BLM) protocol enables users to effortlessly lend, borrow, and earn interest with their digital assets. (https://benqi.fi)",
      "Stargate is a fully composable liquidity transport protocol that lives at the heart of Omnichain DeFi (https://stargate.finance)",
    ],
    subgraphURL: "https://api3.waterfalldefi.org/subgraphs/name/waterfall/qiStarUsdc",
    isRetired: false,
  },
];
